from aioboto3_hints.iam.client import Client
from aioboto3_hints.iam.service_resource import (AccessKey, AccessKeyPair,
                                                 AccountPasswordPolicy,
                                                 AccountSummary,
                                                 AssumeRolePolicy, CurrentUser,
                                                 Group, GroupPolicy,
                                                 InstanceProfile, LoginProfile,
                                                 MfaDevice, Policy,
                                                 PolicyVersion, Role,
                                                 RolePolicy, SamlProvider,
                                                 ServerCertificate,
                                                 ServiceResource,
                                                 SigningCertificate, User,
                                                 UserPolicy, VirtualMfaDevice,
                                                 groups, instance_profiles,
                                                 policies, roles,
                                                 saml_providers,
                                                 server_certificates, users,
                                                 virtual_mfa_devices)

__all__ = (
    'Client',
    'ServiceResource',
    'AccessKey',
    'AccessKeyPair',
    'AccountPasswordPolicy',
    'AccountSummary',
    'AssumeRolePolicy',
    'CurrentUser',
    'Group',
    'GroupPolicy',
    'InstanceProfile',
    'LoginProfile',
    'MfaDevice',
    'Policy',
    'PolicyVersion',
    'Role',
    'RolePolicy',
    'SamlProvider',
    'ServerCertificate',
    'SigningCertificate',
    'User',
    'UserPolicy',
    'VirtualMfaDevice',
    'groups',
    'instance_profiles',
    'policies',
    'roles',
    'saml_providers',
    'server_certificates',
    'users',
    'virtual_mfa_devices',
)
