from aioboto3_hints.ec2.client import Client
from aioboto3_hints.ec2.service_resource import (ClassicAddress, DhcpOptions,
                                                 Image, Instance,
                                                 InternetGateway, KeyPair,
                                                 KeyPairInfo, NetworkAcl,
                                                 NetworkInterface,
                                                 NetworkInterfaceAssociation,
                                                 PlacementGroup, Route,
                                                 RouteTable,
                                                 RouteTableAssociation,
                                                 SecurityGroup,
                                                 ServiceResource, Snapshot,
                                                 Subnet, Tag, Volume, Vpc,
                                                 VpcAddress,
                                                 VpcPeeringConnection,
                                                 classic_addresses,
                                                 dhcp_options_sets, images,
                                                 instances, internet_gateways,
                                                 key_pairs, network_acls,
                                                 network_interfaces,
                                                 placement_groups,
                                                 route_tables, security_groups,
                                                 snapshots, subnets, volumes,
                                                 vpc_addresses,
                                                 vpc_peering_connections, vpcs)

__all__ = (
    'Client',
    'ServiceResource',
    'ClassicAddress',
    'DhcpOptions',
    'Image',
    'Instance',
    'InternetGateway',
    'KeyPair',
    'KeyPairInfo',
    'NetworkAcl',
    'NetworkInterface',
    'NetworkInterfaceAssociation',
    'PlacementGroup',
    'Route',
    'RouteTable',
    'RouteTableAssociation',
    'SecurityGroup',
    'Snapshot',
    'Subnet',
    'Tag',
    'Volume',
    'Vpc',
    'VpcPeeringConnection',
    'VpcAddress',
    'classic_addresses',
    'dhcp_options_sets',
    'images',
    'instances',
    'internet_gateways',
    'key_pairs',
    'network_acls',
    'network_interfaces',
    'placement_groups',
    'route_tables',
    'security_groups',
    'snapshots',
    'subnets',
    'volumes',
    'vpc_addresses',
    'vpc_peering_connections',
    'vpcs'
)
